### ISSUE TITLE
Running in Admin Mode

### ISSUE THREAD

**Issue by johnpierson** [mitevpi/thesaurus#3]
Right now it appears you have to run Revit as an administrator (right click run as admin) in order for the tool to create the following files for read and write. (This is fine, once I realized that needed to happen)

![image](https://user-images.githubusercontent.com/15744724/48086764-db0c8e80-e1ba-11e8-80a1-a5d77e5bda49.png)

**Comment by QilongTang** [comment]
Our first issue 🙌

**Comment by mitevpi** [comment]
@johnpierson always good to have your feedback on my/our work! That's an odd one for sure - I know these days more and more companies are locking down 'admin rights' to their employees' machines, so we should avoid that as much as possible. 

And thanks! - it's exciting that the base functionality is there for sure, but I'd love to actually get in the weeds with some deep/wide RNNs and start making intelligent predictions/thinking more than 3 or 4 steps ahead...

**Comment by johnpierson** [comment]
Glad to contribute to the conversation! I hope to contribute further in the future. After AU I will be sure to keep an eye on this one. 😄

**Comment by andydandy74** [comment]
Why not store this in ```%appdata%``` instead?

**Comment by mitevpi** [comment]
fixed in #7
